### ISSUE TITLE
Map `creator` if `author` not present

### ISSUE THREAD

**Issue by elichad** [ResearchObject/ro-crate-zenodo#20]
Currently only maps `author`, but `creator` may be used instead.

**Comment by rsirvent** [comment]
I have been testing ro-crate-zenodo with COMPSs and this is exactly the case of COMPSs generated RO-Crates (I use `creator` instead of `author`). I can't remember when, but at some point I switched from `author` to `creator` because either the spec or some profile recommended it.

You can find examples of COMPSs RO-Crates in WorkflowHub: https://workflowhub.eu/workflows?filter%5Bworkflow_type%5D=pycompss

Let me know if I can help.

**Comment by elichad** [comment]
I don't have a lot of time to work on this package currently, so I would welcome a PR to fix this issue :)

**Comment by rsirvent** [comment]
Yeah, same here, time is tight. Anyway, if this package is deprecated then I'll try to check if ro-crate-inveniordm has the same issue, and continue the discussion there.

**Comment by elichad** [comment]
Superseded by https://github.com/ResearchObject/ro-crate-inveniordm/issues/34 (see also #23)
